# Generated by Django 4.2.4 on 2023-08-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=15)),
                ('mobile_no', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
