# Generated by Django 4.2.4 on 2023-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('course', models.CharField(max_length=10)),
                ('Trainer', models.CharField(max_length=10)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
