# Generated by Django 4.2.4 on 2023-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNumber', models.IntegerField()),
                ('Password', models.CharField(max_length=15)),
                ('Confirm_Password', models.CharField(max_length=15)),
            ],
        ),
    ]
