# Generated by Django 4.2.4 on 2023-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
